# Copyright (c) 2019. TIBCO Software Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

# docker-compose.yml example for JasperReports Server

version: '3'

services:
  jasperserver-pro:
    image: jasperserver-pro:init-test
    
    build: .
    
    # expose port on the host
    ports:
      - "8080:8080"
      - "8443:8443"
    
    # set depends on js_database Postgresql service
    depends_on:
      - jasperserver_pro_repository
    
    # point to env file with key=value entries 
    env_file: .env
    
    # setting following values here will override settings from env_file
    environment:
      - DB_HOST=jasperserver_pro_repository
      - JRS_LOAD_SAMPLES=true

    #volumes:
      # where jasperserver.license file is. Otherwise uses temporary license
      #- jrs_license:/usr/local/share/jasperreports-pro/license 
      
      # zip files in alphabetical order exploded into webapps/jasperserver-pro
      #- jrs_customization:/usr/local/share/jasperreports-pro/customization
      
      # zip files in alphabetical order exploded into $CATALINA_HOME
      #- jrs_tomcat_customization:/usr/local/share/jasperserver-pro/tomcat-customization
      
      # .keystore files in this volume loaded into /root.
      # needs KS_PASSWORD environment variable set
      #- jrs_keystore:/usr/local/share/jasperserver-pro/keystore
      
      # default_master_additional.properties file added to default_master.properties
      # see "To install the WAR file using js-install scripts" in JasperReports Server Installation Guide
      #- jrs_deploy_customization:/usr/local/share/jasperserver-pro/deploy-customization
      
      # include a new version of a JDBC driver for repository databases supported by 
      # JasperReports Server.
      # valid dbTypes are: postgresql, mysql, sqlserver, oracle, db2
      #- /path/to/JDBC/driver:/usr/src/jasperreports-server/buildomatic/conf_source/db/<dbType>/jdbc
      # set environment property:
      # maven.jdbc.version=<version # of JDBC driver>
      # have a look at buildomatic/conf_source/db/<dbType> for db.properties for a dbType
      
      # for Mac OS you may want to define local path for volume mounts. 
      # Note that defining path for a named volume is not supported 
      # by Compose. For example:
      # - /some-local-path:/usr/local/tomcat/webapps/jasperserver-pro
      # - ~/jasperreports-pro/license:/usr/local/share/jasperreports-pro/license
      # - /tmp/customization:/usr/local/share/jasperreports-pro/customization
      #
      # Under Docker for Windows, volumes have to be under the logged in user's User area
      #  - /C/Users/aUser/Documents/License:/usr/local/share/jasperserver-pro/license 
 
 # sample databases too if configured
  jasperserver_pro_repository:
    image: postgres:10
    env_file: .env
    
    volumes:
      - postgres-10-data:/var/lib/postgresql/data

volumes:
  postgres-10-data:
  #jrs_license:
  #jrs_customization:
