apiVersion: v2
name: scalable-query-engine-scaling
description: Scalable Query Engine custome scaling
type: application
version: 1.0.0
appVersion: 8.1.1
maintainers:
  - name: Jaspersoft Eng Infra
    email: js-eng-infra@tico.com
dependencies:
  - name: prometheus-adapter
    version: "2.15.2"
    repository: "@prometheus-community"
    condition: prometheusAdapter.enabled
    tags:
      - monitoring
      - autoscaling
      - prometheus
  - name: prometheus
    version: "14.7.1"
    repository: "@prometheus-community"
    condition: prometheusAdapter.enabled
    tags:
      - monitoring
      - autoscaling
      - prometheus