# kubectl apply -f .\jasperreports-server-kube.yml
# kubectl delete -f .\jasperreports-server-kube.yml
apiVersion: v1
kind: Service
metadata:
  name: jasperreports-server
  labels:
    app: jasperreports-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: jasperreports-server
  selector:
    app: jasperreports-server
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jasperreports-server
  labels:
    app: jasperreports-server
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jasperreports-server
    spec:
      containers:
      - name: jasperreports-server
        image: jasperserver-pro:7.5.0
        env:
          - name: DB_HOST
            value: postgresql
          - name: DB_NAME
            value: jasper-k8s
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: https
            containerPort: 8443
            protocol: TCP
        volumeMounts:
        - name: license
          mountPath: "/usr/local/share/jasperserver-pro/license"
          readOnly: true
        - name: jasperreports-server-volume
          mountPath: "/usr/local/share/jasperserver-pro"
          readOnly: false
      initContainers:
      - name: init
        image: jasperserver-pro-cmdline:7.5.0
        env:
          - name: DB_HOST
            value: postgresql
          - name: DB_NAME
            value: jasper-k8s
          - name: JRS_LOAD_SAMPLES
            value: "true"
        volumeMounts:
        - name: license
          mountPath: "/usr/local/share/jasperserver-pro/license"
          readOnly: true
        - name: jasperreports-server-volume
          mountPath: "/usr/local/share/jasperserver-pro"
          readOnly: false
      volumes:
      - name: license
        secret:
          secretName: jasperreports-server-license
      - name: jasperreports-server-volume
        persistentVolumeClaim:
          claimName: jasperreports-server-pv-claim
