# kubectl apply -f .\jasperreports-server-k8s.yml
# kubectl delete -f .\jasperreports-server-k8s.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jasper-config
  namespace: jaspersoft
data:
  DB_HOST: postgresql
  DB_NAME: jasperserver-k8s
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  JRS_LOAD_SAMPLES: "true"
  #KEYSTORE_SECRET_NAME: '"jasperserver-pro-jrsks"'
---
apiVersion: v1
kind: Service
metadata:
  name: jasperserver-pro
  labels:
    app: jasperserver-pro
spec:
  ports:
    - port: 80
      targetPort: 80
      name: jasperserver-pro
  selector:
    app: jasperserver-pro
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jasperserver-pro
  labels:
    app: jasperserver-pro
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jasperserver-pro
    spec:
      containers:
      - name: jasperserver-pro
        image: jasperserver-pro:7.8.0
        imagePullPolicy: Always
      - envFrom:
        - configMapRef:
            name: jasper-config
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
        volumeMounts:
        - name: license
          mountPath: "/usr/local/share/jasperserver-pro/license"
          readOnly: true
        - name: jasperserver-pro-volume
          mountPath: "/usr/local/share/jasperserver-pro"
          readOnly: true
      initContainers:
      - name: init
        image: jasperserver-pro-cmdline:7.8.0
      - envFrom:
        - configMapRef:
            name: jasper-config
        volumeMounts:
        - name: license
          mountPath: "/usr/local/share/jasperserver-pro/license"
          readOnly: true
        - name: jasperserver-pro-volume
          mountPath: "/usr/local/share/jasperserver-pro"
          readOnly: false
      volumes:
      - name: license
        secret:
          secretName: jasperserver-pro-license
      - name: jasperserver-pro-volume
        persistentVolumeClaim:
          claimName: jasperreports-server-pv-claim
